service_name: verse-http
description: testing http plugin
plugins:
  - name: shrine
    config:
      storages:
        - name: default
          adapter: file_system
          config:
            path: tmp/storage/default
        - name: other
          adapter: file_system
          config:
            path: tmp/storage/other
logging:
  level: warn
